make:
	g++ -std=c++11  -c /home/shankz/Documents/QA/Phase3/BankingSystem/AccountHelper.cpp -o .objs/AccountHelper.o
	g++ -std=c++11  -c /home/shankz/Documents/QA/Phase3/BankingSystem/BankingSystem.cpp -o .objs/BankingSystem.o
	g++ -std=c++11  -c /home/shankz/Documents/QA/Phase3/BankingSystem/FileStreamHelper.cpp -o .objs/FileStreamHelper.o
	g++ -std=c++11  -c /home/shankz/Documents/QA/Phase3/BankingSystem/stdafx.cpp -o .objs/stdafx.o
	g++ -std=c++11  -c /home/shankz/Documents/QA/Phase3/BankingSystem/TransactionsHelper.cpp -o .objs/TransactionsHelper.o
	g++  -o BankingSystem/BankingSystem .objs/AccountHelper.o .objs/BankingSystem.o .objs/FileStreamHelper.o .objs/stdafx.o .objs/TransactionsHelper.o    
 

